# Generated by Django 4.2.3 on 2023-07-09 23:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0003_messsage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messsage',
            new_name='Message',
        ),
    ]
